### ISSUE TITLE
Results page showing 0 issues

### ISSUE THREAD

**Issue by emenda-support** [Emenda/klocwork-plugin#12]
<img width="495" alt="1" src="https://user-images.githubusercontent.com/23738783/28212534-cb7cba58-6899-11e7-94c3-edc55e6df7fd.png">
<img width="1303" alt="2" src="https://user-images.githubusercontent.com/23738783/28212535-cb85925e-6899-11e7-8b62-e0a732141751.png">

It looks like there is a bug that the results page is now showing everything as 0

**Comment by michael-baron** [comment]
the publish step is being deprecated and its replacement should resolve this bug
