### ISSUE TITLE
"Publish Integration Results" not compatible with Pipeline

### ISSUE THREAD

**Issue by phoenikz** [Emenda/klocwork-plugin#23]
A nice way to publish issue trend and server link for Pipeline builds would be great (at least documentation should be clear that this feature is not supported for Pipelines), but a rework of the publisher to work with Pipeline would be appreciated.

**Comment by michael-baron** [comment]
Thanks for the raised issue. We are in the process of creating new steps/code that replaces the features of the old publish step (that you correctly noticed does not work with pipelines). These will obviously be pipeline friendly.

**Comment by germaino** [comment]
Hello, Do you have a rough idea on when you plan to deliver it ? thanks

**Comment by michael-baron** [comment]
The functionality of the old publish step has how been replicated in the new quality gate steps and the integration analysis load step. Both these steps are pipeline compatible.
