### ISSUE TITLE
Add "(Optional)" to the ltoken field

### ISSUE THREAD

**Issue by andreaslarfors** [Emenda/klocwork-plugin#3]
The ltoken field in the Build Environment configuration of the Klocwork plug-in has the following help text:

> Specify a custom ltoken location. The Klocwork ltoken is used to authenticate with the Klocwork server. More information

It is not clear that this an optional value to enter - if no value is entered then the default ltoken location is used, which should work for most users. The text should be updated to

> (Optional) Specify a custom ltoken location. The Klocwork ltoken is used to authenticate with the Klocwork server. More information

**Comment by jlarfors** [comment]
Fixed!
