### ISSUE TITLE
FR: Automatic Project Creation (kwadmin create-project)

### ISSUE THREAD

**Issue by andreaslarfors** [Emenda/klocwork-plugin#50]
This would be a useful feature: if the Klocwork project does not exist, create it using kwadmin create-project. Currently we are having to do this manually with a slight mess of environment variables etc.

Perhaps this is best as a separate build step for greater flexbility.

**Comment by michael-baron** [comment]
> This would be a useful feature: if the Klocwork project does not exist, create it using kwadmin create-project. Currently we are having to do this manually with a slight mess of environment variables etc.
> 
> Perhaps this is best as a separate build step for greater flexbility.

Agreed. Come across this one as well recently, especially relevant for branch pipelines. In my todo list unless someone gets to it first

**Comment by jlarfors** [comment]
I think it would be nice as a checkbox under the kwvuildproject/kwadmin step.
"Create non-existing project automatically" or something

**Comment by michael-baron** [comment]
added in 2.5.9
