### ISSUE TITLE
Pipeline Snippet Generator: no public field ‘reportConfig’

### ISSUE THREAD

**Issue by andreaslarfors** [Emenda/klocwork-plugin#51]
When using the pipeline snippet generator on klocworkIntegrationStep2, the following error is shown:

no public field ‘reportConfig’ (or getter method) found in class com.emenda.klocwork.pipeline.KlocworkServerLoadStep

To reproduce:
1. Create a new Pipeline job
2. Go to the Pipeline step of the job
3. Click "Pipeline Syntax"
4. Select klocworkIntegrationStep2 from the drop down list in the Snippet Generator

**Comment by jlarfors** [comment]
This is still an issue:
![image](https://user-images.githubusercontent.com/1135394/55567441-aa7a4380-56cb-11e9-8149-e0ceea5335a1.png)

Would be great if the reportConfig owner could fix this

**Comment by michael-baron** [comment]
fixed in 2.4.7
