### ISSUE TITLE
Potential bug from recent pull request merge "JCasC" 

### ISSUE THREAD

**Issue by michael-baron** [Emenda/klocwork-plugin#55]
https://github.com/Emenda/klocwork-plugin/pull/54

I set up a fresh Jenkins server (2.4.6 plugin) on a linux vm and when adding a new server and installation to the global setting: Manage Jenkins -> Configure System -> klocwork ->add klocwork server button -> save.

once saved the server is not available to select on the freestyle job configuration page and going back to the global setting the configuration does not exist.

Need to confirm by creating a fresh (2.4.5 plugin) server and seeing if we get the same

**Comment by benemenda** [comment]
Is this with the JCasC plugin (latest) installed too?

**Comment by michael-baron** [comment]
resolved in 2.4.7
