### ISSUE TITLE
Publish Step doesnt pick-up KLOCWORK_LTOKEN var when set through Jenkins

### ISSUE THREAD

**Issue by emenda-support** [Emenda/klocwork-plugin#8]
The current version of kwjlib used looks at the java get env vars to find the KLOCWORK_LTOKEN var, but when setting the KLOCWORK_LTOKEN through Jenkins via properties it doesnt pick this up.

Solution will be to add a constructor to kwjlib to take the ltoken location that way the kwjlib stays generic. We can then check for existance of the ltoken using the var and call this constructor if true.

**Comment by jlarfors** [comment]
If kwjlib gets the ltoken from getenv, then KLOCWORK_LTOKEN should be set and retrievable by kwjlib? And if not, then a way to pass the environment could be another option?

I think using the KW API should be handled entirely with kwjlib, not code using it with "if env set use this"?

**Comment by emenda-support** [comment]
Yes kwjlib uses the java getenv() to get the enviroment vars, however when environment variables are set through Jenkins using things like the envinject plugin this doesnt work. To get these enviroment variables set through jenkins we need to use Jenkins' EnvVars, which isnt available within kwjlib as it is not Jenkins specific.

So the suggested fix is to check EnvVars for KLOCWORK_LTOKEN and if it has been set pass the value (path-location-string) to kwjlib via the cosntructor.

**Comment by jlarfors** [comment]
EnvVars is just a sub class to a map of string to string, so kwjlib could accept that as a parameter and you could pass EnvVars directly down. Either way works I guess, just want to avoid "extra" code outside the library

**Comment by emenda-support** [comment]
Yea, thought of that. Will see when I get round to it what seems clean. Depending on what EnvVars.get() returns when the env isnt set I can always just call the kwjlib constructor as: KWApi myObj = new KWApi(url, EnvVars.get("KLOCWORK_LTOKEN") );. Then if the EnvVars.get() is null or empty string I can handle the proceed as normal within kwjlib.

**Comment by jlarfors** [comment]
That's another clean approach. StringUtils.isEmpty(string) is good for this as it returns true if null or empty.

**Comment by emenda-support** [comment]
Resolved v2.1
